parameters:
#    kunstmaan_new_relic.example.class: Kunstmaan\NewRelicBundle\Example

services:
#    kunstmaan_new_relic.example:
#        class: %kunstmaan_new_relic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    kunstmaan_new_relic.transactionname:
        class: Kunstmaan\NewRelicBundle\EventListener\TransactionNameListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: setTransactionName }
            
    kunstmaan_new_relic.custom_metrics:
        class: Kunstmaan\NewRelicBundle\Helper\CustomMetrics
